<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventHab.Application\EventHab.Application.csproj" />
      <ProjectReference Include="..\EventHub.Domain\EventHub.Domain.csproj" />
    </ItemGroup>

</Project>
